StockMaster/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('StockMaster_app.urls')),
    path('admin/', admin.site.urls),
]

StockMaster_app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('productos/',views.productos,name='productos'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('usuarios/eliminaruser/<int:id>', views.eliminaruser, name="eliminaruser"),
    path('soporte/', views.soporte, name='soporte'),
    path('comentario/',views.comentario),
    path('productos/eliminarcomentarios/<int:idcomentario>/', views.eliminarcomentarios, name='eliminar_comentario'),
    path('contestarcomentarios/<int:idcomentario>/', views.contestarcomentarios, name='contestarcomentarios'),
    path('inventario', views.example_view, name='inventario'),
    path('pro/', views.pro, name='pro'),
    path('registrarProducto/', views.registrarProducto),
    path('pro/edicioninventario/<idproducts>', views.edicioninventario),
    path('editarProducto/', views.editarProducto),
    path('pro/eliminaInventario/<idproducts>', views.eliminaInventario),
    path('config', views.configuraciones, name='configuraciones77'),
    path('registrar_categoria/', views.registrar_categoria, name='registrar_cat'),
    path('edicioncategoria/<int:categoria_id>/', views.edicion_categoria, name='edicionicat'),
    path('editarCat/', views.editarCat, name='editar_cat'),
    path('get_char/', views.get_char, name='get_char'),
    path('eliminar_categoria/<int:categoria_id>/', views.eliminar_categoria, name='eliminarcategoria'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.exit, name='exit'),
    ]

StockMaster_app/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image  
from django.utils import timezone
# Create your models here.
class Categoria(models.Model):
    categoria_id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Productos(models.Model):
    idproducts = models.AutoField(primary_key=True)
    codigo = models.CharField(max_length=255)
    nombre = models.CharField(max_length=50)
    precio = models.PositiveBigIntegerField()
    marca = models.CharField(max_length=255)
    cantPro = models.CharField(max_length=255)
    imagen = models.BinaryField(null=True, blank=True)

    id_categorias = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nombre, self.precio)
    
class Mensajes(models.Model):
    idcomentario = models.AutoField(primary_key=True)
    comentario = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    tiempo_creacion = models.DateTimeField(default=timezone.now)
    respuestascomentarios=models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.comentario

StockMaster_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from django import forms
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib import messages as men
from django.contrib.auth.decorators import user_passes_test
from django.core.files import File
from django.conf import settings
from pathlib import Path, os
from .models import Productos, Mensajes, Categoria
from django.http.response import JsonResponse
import base64
from PIL import Image  
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.core.exceptions import MultipleObjectsReturned

# Create your views here.

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required. Enter your first name.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required. Enter your last name.')
    email = forms.EmailField()
    
def is_superuser(user):
    return user.is_authenticated and user.is_superuser

@user_passes_test(is_superuser)
@login_required(login_url='signin')
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            email = form.cleaned_data.get('email')
            user.email = email
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            is_superuser = form.cleaned_data.get('is_superuser')
            if is_superuser is not None and is_superuser.isdigit():
                user.is_superuser = bool(int(is_superuser))
            if 'user_img' in request.FILES:
                user.user_img = request.FILES['user_img']
                        # Guarda la imagen de usuario

            user.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            
            return redirect('/usuarios')
        else:
            # Maneja los errores específicos y agrega mensajes de error según corresponda
            if 'email' in form.errors:
                messages.error(request, 'error en la escritura de gmail recomendacion "@gmail.com" "@hotmail.com" "outlook.com"')
            
            if 'username' in form.errors:
                messages.error(request, 'El nombre de usuario ya existe. Por favor, elige otro.')
            else:
                messages.error(request, 'La contraseña debe de tener más de 8 caracteres y no deben ser numeros continuos')
            # Agrega otros mensajes de error personalizados según tus necesidades
            if 'is_superuser' in form.errors:
                messages.error(request, 'error de admin')
    else:
        form = CustomUserCreationForm()

    return render(request, 'StockMaster_app/registro.html', {'form': form})

def eliminaruser(request, id):
    try:
        user_to_delete = User.objects.get(id=id)
        user_to_delete.delete()
        return redirect('/usuarios')
    except User.DoesNotExist:
        # Maneja el caso en que el usuario con el ID especificado no existe
        # Puedes mostrar un mensaje de error o realizar alguna otra acción aquí
        pass
    
def signin(request):
    if request.user.is_authenticated:
        return redirect('/productos')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = User.objects.create_user(username=username, password=password)
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('productos')
        else:
            form = AuthenticationForm(request.POST)
            messages.error(request, 'Contraseña Incorrecta', extra_tags='signin')

    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})
def home(request):
    if request.user.is_authenticated:
        return redirect('/productos')
  #  mensajes = Mensajes.objects.all()
  #  cantidad_mensajes =mensajes.count()
    return render(request, 'registration/login.html')

@login_required(login_url='signin')
def productos(request):
    mensajes = Mensajes.objects.all()
    cantidad_mensajes = mensajes.count()
    return render(request, 'StockMaster_app/productos.html', {'Mensajes': mensajes, 'cantidad_mensajes':cantidad_mensajes})

@login_required(login_url='signin')
def usuarios(request):
    if request.user.is_superuser:
        mensajes = Mensajes.objects.all()
        cantidad_mensajes =mensajes.count()
        form = User.objects.all()  # Agrega los paréntesis para instanciar el formulario
        return render(request, 'StockMaster_app/usuarios.html', {'Usuarios': form, 'Mensajes':mensajes,'cantidad_mensajes':cantidad_mensajes})
    else:
        return redirect('/productos')
    
@login_required(login_url='signin')
def exit(request):
    logout(request)
    return redirect('/productos')

@login_required(login_url='signin')
def pro(request):
    if request.user.is_superuser:
        mensajes = Mensajes.objects.all()
        cantidad_mensajes =mensajes.count()
        ProductosListados = Productos.objects.all()
        CategoriaListados = Categoria.objects.all() 
        for producto in ProductosListados:
            producto.imagen_url = get_imagen_url(producto.imagen)
        return render(request, 'StockMaster_app/inventario.html', { "Productos": ProductosListados,"Categoria": CategoriaListados, 'Mensajes':mensajes, 'cantidad_mensajes':cantidad_mensajes})
    else:
        return redirect('/productos')
    
def get_imagen_url(imagen_binaria):
    imagen_base64 = base64.b64encode(imagen_binaria).decode('utf-8')
    return f"data:image/jpeg;base64,{imagen_base64}"

@login_required(login_url='signin')
def registrarProducto(request):
    codigo = request.POST['txtCodigo']
    nombre = request.POST['txtNombre']
    precio = request.POST['NumPrecio']
    marca = request.POST['NomMarca']
    cantPro = request.POST['CantPro'] 
    imagen = request.FILES['imagen'] 
    categoria_id = request.POST['categoria']

    # Comprobar si el producto ya existe
    if Productos.objects.filter(codigo=codigo).exists():
        messages.error(request, '¡El producto con este código ya existe!')
    elif Productos.objects.filter(marca=marca, nombre=nombre).exists():
        messages.error(request, 'Este producto ya existe!')
    else:
        # Leer los datos de la imagen como bytes
        imagen_bytes = imagen.read()
        
        # Crear una instancia de Producto con los datos proporcionados, incluyendo la imagen como bytes
        producto = Productos(codigo=codigo, nombre=nombre, precio=precio, marca=marca, cantPro=cantPro, imagen=imagen_bytes, id_categorias_id=categoria_id)
        # Guardar la instancia en la base de datos
        producto.save()
        messages.success(request, '¡Producto registrado!')
    return redirect('/pro/')

@login_required(login_url='signin')
def edicioninventario(request, idproducts):
    productos = Productos.objects.get(idproducts= idproducts)
    CategoriaListados = Categoria.objects.all() 
    imagen_url = get_imagen_url(productos.imagen)
    return render(request, "StockMaster_app/edicioninventario.html", {"productos": productos, "imagen_url": imagen_url, "Categoria": CategoriaListados})

@login_required(login_url='signin')
def editarProducto(request):
    idproducts = request.POST.get('idproducts')
    codigo = request.POST.get('txtCodigo')
    nombre = request.POST.get('txtNombre')
    precio = request.POST.get('NumPrecio')
    marca = request.POST.get('NomMarca')
    cantPro = request.POST.get('CantPro')
    nueva_imagen = request.FILES.get('imagen') 
    categoria_id = request.POST.get('categoria') 

    productos = Productos.objects.get(idproducts=idproducts)

    productos.codigo = codigo
    productos.nombre = nombre
    productos.precio = precio
    productos.marca = marca
    productos.cantPro = cantPro
    productos.id_categorias_id = categoria_id
    if nueva_imagen:
        productos.imagen = nueva_imagen.read()
    productos.save()

    messages.success(request, '¡Producto Editado!')
    return redirect('/pro/')

@login_required(login_url='signin')
def eliminaInventario(request, idproducts):
    productos = Productos.objects.get(idproducts=idproducts)
    productos.delete()
    messages.success(request, '¡Producto Eliminado!')
    return redirect('/pro')

def get_char(_request):
    chart = {}
    return JsonResponse(chart)

#mio gael
@login_required(login_url='signin')
def soporte(request):
    mensajes = Mensajes.objects.all()
    cantidad_mensajes = mensajes.count()
    return render(request, 'StockMaster_app/soporte.html', {'Mensajes': mensajes,  'cantidad_mensajes': cantidad_mensajes})

@login_required(login_url='signin')
def comentario(request):
    if request.method == 'POST':

StockMaster_app/templates/StockMaster_app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Título de la Página{% endblock %}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">     
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <style>
    </style>
</head>
<body>
<div class="container py-4">
     {% block body %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/inventario.js' %}"></script>
<script src="{% static 'js/edit.js' %}"></script>
<script src="{% static 'usuarios/js/dashboard.js' %}"></script>
<script src="{% static 'productos/js/ordenes.js' %}"></script>

</body>
</html>

StockMaster_app/templates/StockMaster_app/edicion_categoria.html
{% extends "./base.html" %}
{% block title %} Gestión de Categoria {% endblock %}
{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Edición de Categoria</h2>
        <div class="card">
            <div class="card-body">
                {% if error_messages %}
                <div class="alert alert-danger" id="error-alert">
                    <ul>
                        {% for message in error_messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <script>
                    setTimeout(function() {
                        var errorAlert = document.getElementById('error-alert');
                        if (errorAlert) {
                            errorAlert.style.display = 'none';
                        }
                    }, 5000); 
                </script>
                {% endif %}
                <form action="/editarCat/" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="form-group py-2">
                        <input type="hidden" name="idCat" value="{{ categoria.categoria_id }}">

                    </div>
                    <div class="form-group py-2">
                        <input type="text" id="txtNombreCat" name="txtNombreCat" value="{{categoria.nombre}}" pattern="[A-Za-z0-9]{6,}" class="form-control" placeholder="Nombre"  minlength="6" maxlength="20" required>
                        <span class="error-message" style="color: red;"></span>
                    </div>                      
                    <div class="form-group py-2">
                        <button type="submit" class="btn btn-success btn-lg btn-block text-white">Guardar</button>
                        <button type="submit" class="btn btn-danger btn-lg btn-block text-white">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>
    </div> 
    <script>
        const txtNombreCat = document.getElementById("txtNombreCat");

    // Agrega un evento 'input' al campo de texto
    txtNombreCat.addEventListener("input", function () {
        // Convierte el valor del campo de texto en mayúsculas
        this.value = this.value.toUpperCase();
    });

    var campoId = 'txtNombreCat';
    var campo = document.getElementById(campoId);

    campo.addEventListener('input', function () {
        var input = this;
        var errorMessage = input.parentNode.querySelector('.error-message');

        if (input.validity.patternMismatch) {
            errorMessage.textContent = 'El nombre debe contener almenos 6 caracteres alfanuméricos';
        } else {
            errorMessage.textContent = '';
        }
    });
    </script>
</div>
{% endblock %}

StockMaster_app/templates/StockMaster_app/edicioninventario.html
{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Título de la Página{% endblock %}</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">     
     <link rel="stylesheet" href= "{% static 'usuarios/css/agregarProductos.css' %}">
    <style>
    </style>
</head>
<body>
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <h2>Edición de Productos</h2>
            <div class="card">
                <div class="card-body">
                    {% if error_messages %}
                    <div class="alert alert-danger" id="error-alert">
                        <ul>
                            {% for message in error_messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <script>
                        setTimeout(function() {
                            var errorAlert = document.getElementById('error-alert');
                            if (errorAlert) {
                                errorAlert.style.display = 'none';
                            }
                        }, 5000); 
                    </script>
                    {% endif %}
                    <form action="/editarProducto/" method="POST" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-columns">
                            <!--Primer columna-->
                            <div class="form-column">
                                <div class="form-group">
                                    <input type="hidden" name="idproducts" value="{{ productos.idproducts }}">
                                </div>
                                <div class="form-group py-2">
                                    <input type="text" id="txtCodigo" name="txtCodigo" value="{{ productos.codigo }}" class="form-control" placeholder="Codigo" pattern="[A-Za-z0-9]{6}" maxlength="6" required>
                                    <span class="error-message" style="color: red;"></span>
                                </div>
                                <div class="form-group py-2">
                                    <input type="text" id="txtNombre" name="txtNombre" value="{{productos.nombre}}" class="form-control" placeholder="Nombre"  minlength="6" maxlength="20" required>
                                    <span class="error-message" style="color: red;"></span>
                                </div>
                                <div class="form-group py-2">
                                    <input type="text" id="NumPrecio" name="NumPrecio" placeholder="Precio" value="{{productos.precio}}" pattern="[0-9]{1,7}" class="form-control" maxlength="7" required>
                                    <small class="text-muted">Ingrese un número (entre 1 y 100 000).</small><br>
                                    <span class="error-message error" style="color: red;"></span>
                                </div>

                            </div>

                            <!--Segunda columna-->
                            <div class="form-column">
                                <div class="form-group py-2">
                                    <input type="text" id="NomMarca" name="NomMarca" class="form-control" value="{{productos.marca}}"  placeholder="Marca" minlength="6" maxlength="20" required>
                                    <span class="error-message" style="color: red;"></span>
                                </div>                
                                <div class="form-group py-2">
                                    <input type="text" id="CantPro" name="CantPro" placeholder="Cantidad de Producto" pattern="[0-9]{1,7}" value="{{productos.cantPro}}"class="form-control" maxlength="7" required>
                                    <small class="text-muted">Ingrese un número (entre 1 y 100 000).</small><br>
                                    <span class="error-message error" style="color: red;"></span>
                                </div>
                                <div class="update">
                                    <div class="message"></div>
                                        <label for="categoria">Categoría:</label>
                                        <br>
                                        <select name="categoria" id="categoria" class="updatess" required>
                                            <option value="" disabled selected>Selecciona una categoría</option>
                                            {% for c in Categoria %}
                                                <option value="{{ c.categoria_id }}">{{ c.nombre }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="form-column">
                                <div class="form-group py-2">
                                    {% if imagen_url %}
                                    <img src="{{ imagen_url }}" alt="Imagen actual" width="200">
                                    
                                    {% else %}
                                    <p>No hay imagen disponible.</p>
                                    {% endif %}
                                </div>
                                <div class="form-group py2">
                                    <label for="id_imagen">Imagen actual</label>
                                </div>
                            
                                <div class="form-group py-2">
                                    <label for="imagen">Nueva imagen:</label>
                                    <input type="file" name="imagen" id="id_imagen" accept="image/*">
                                    <input type="hidden" name="imagen_actual" value="{{ productos.imagen.url }}">
                                </div>
                            </div>
                            <div class="form-group py-2">
                                <button type="submit" class="btn btn-success btn-lg btn-block text-white">Guardar</button>
                                <a type="submit" class="btn btn-danger btn-lg btn-block text-white" href="{% url 'pro' %}">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
        </div> 
    </div>
            <script src="{% static 'js/inventario.js' %}"></script>
          <script src="{% static 'js/edit.js' %}"></script>
</body>
</html>
{% endblock %}


StockMaster_app/templates/StockMaster_app/example.html
{% extends "./base.html" %}
{% block title %} Productos {% endblock %}
{% block body %}
<div class="container">
    <h1 class="mt-4">Productos</h1>
    <form method="get" class="mb-4">
        <div class="form-group">
            <label for="categoria">Categoría:</label>
            <select name="categoria" id="categoria" class="form-control" required>
                <option value="" disabled selected>Selecciona una categoría</option>
                {% for categoria in Categoria %}
                    <option value="{{ categoria.nombre }}">{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Filtrar</button>
        <a href="/example" class="btn btn-secondary">Mostrar todos los productos</a>
    </form>
    <div class="row">
        {% for producto in Productos %}
            {% if not request.GET.categoria or producto.id_categorias.nombre == request.GET.categoria %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <center><img src="{{ producto.imagen_url }}" alt="{{ producto.nombre }}" class="card-img-top img-fluid" style="max-height: 250px;"></center>
                        <div class="card-body">
                            <h5 class="card-title">{{ producto.nombre }}</h5>
                            <p class="card-text">Código: {{ producto.codigo }}</p>
                            <p class="card-text">Categoría: {{ producto.id_categorias.nombre }}</p>
                            <p class="card-text">Precio: {{ producto.precio }}</p>
                            <p class="card-text">Marca: {{ producto.marca }}</p>
                            <p class="card-text">Cantidad: {{ producto.cantPro }}</p>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>    
</div>
{% endblock %}

StockMaster_app/templates/StockMaster_app/grafica.html
{% extends "./base.html" %}
{% block title %} Gestion de Productos {% endblock %}
{% block body %}


{% block body %}
{% endblock %}

StockMaster_app/templates/StockMaster_app/home.html
{%extends 'StockMaster_app/productos.html'%}

StockMaster_app/templates/StockMaster_app/registro.html


{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="stylesheet"href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link  rel="stylesheet" href="{% static 'usuarios/css/registro.css' %}">
</head>
    <body>
    <div class="container">
        <div class="title">Registro de Usuarios</div>
      
        <form  action="" method="post" id="registrationForm">
            {% csrf_token %}
            {% if messages %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger"><p>{{ message.tags }}:</p> {{ message }}</div>
                {% endfor %}
            {% endif %}
            {% endif %}
            <div class="user-details" id="#IniciaSesion">
                <div class="input-box">
                    <span class="details">Nombre Completo</span>
                    <input type="text" id="first_name" name="first_name" placeholder="Enter your name" required>
                </div>
                <div class="input-box">
                    <span class="details">Apellido</span>
                    <input type="text" id="last_name" name="last_name" placeholder="Enter your last_name" required>
                </div>
                <div class="input-box">
                    <span class="details">Email</span>
                    <input type="email" id="email" name="email" placeholder="Enter your email" required>
                </div>
                
                <div class="input-box">
                    <span class="details">Username</span>
                    <input type="text" id="username" name="username" placeholder="Enter your username" required>
                </div>
                <div class="input-box">
                    <span class="details">Password</span>
                    <input type="password" id="id_password1" name="password1" placeholder="Enter your password" required>
                </div>
                <div class="input-box">
                    <span class="details">Confirm Password</span>
                    <input type="password" id="id_password2" name="password2" placeholder="confirm your password" required>
                </div>
                <div class="input-box">
                    <select name="is_superuser" id="is_superuser" class="updatess" required>
                        <option value="" disabled selected>Selecciona una rol</option>
                        <option value="1">Administrador</option>
                        <option value="0">Empleado</option>
                    </select>
                </div>
            </div>
            <div class="button">
                <button type="submit">Registrar</button>
                
            </div>
        </form>
        <div class="buttonn">
            <form action="{% url 'usuarios' %}">
                <button>Cancelar</button>
            </form>
            
        </div>
    </div>
    
    <script src="{% static 'usuarios/js/aviso.js' %}"></script>
    </body>
</html>
{% endblock %}